default:
  tables_empiric: "./model/data/tables-model-empirical.rds"
  tables_path: "./model/data/tables-model.rds"
  target_dir: "./model/data"
  params_ll: "./data/prolific/results/toy-blocks-pilot-2/results-dirichlet-fits.csv"
  utts_path: "./model/data/utterances-tables-stimuli.rds"
  generate_utterances: false
  seed_tables: 202008
  save: true
  cost_conditional: 0
  alpha: 3
  theta: 0.8
  verbose: true
  cns: !expr c("A implies C", "C implies A", "A implies -C", "C implies -A", "A || C")
  packages:  !expr c(here("model", "model", "node_modules", "conditionalsHelpers"),
                     here("model", "model", "node_modules", "conditionalsDefault"))
  model_path: !expr here("model", "model", "default-model", "default-model.wppl")
  #seed_webppl: !expr as.numeric(Sys.time())
  seed_webppl: 123467
  add_accept_conditions: true
  utt: "A > C"
  vars: !expr c("A", "C")
  bias: "none"

model_tables:
  n_ind_tables: 10000
  n_dep_tables: 2500
  indep_sigma: 0.01
  tables_path: "./model/data/tables-model.rds"
  target_dir: "./model/data"
  target_params: "params-tables-model.rds"

## 2. Level configurations ##
# @arg utt: - if set to "p_delta" or "p_rooij", respective value must be
#           large (see in webppl file) for all states given to the speaker,
#           - if set to "" no condition, just sampled from prior as usual
speaker:
  level_max: "speaker"
  utt: ""
  target_fn: "results-speaker.rds"
  target_params: "params-speaker.rds"
  n_samples: 0 # bns sampled from prior
  #bn_ids: !expr c(5)
  
prior:
  level_max: "prior"
  utt: ""
  target_fn: "results-prior.rds"
  target_params: "params-prior.rds"
  

priorN:
  level_max: "priorN"
  utt: ""
  target_fn: "results-priorN.rds"
  target_params: "params-priorN.rds"
  n_samples: 10000

ll:
  level_max: "LL"
  utt: "A > C"
  target_fn: "results-LL.rds"
  target_params: "params-LL.rds"

pl:
  level_max: "PL"
  utt: "A > C"
  target_fn: "results-PL.rds"
  target_params: "params-PL.rds"


# there needs to be 1 blank final line!
